### ISSUE TITLE
Copy file task

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-workers#11]
We want to a task/worker that copies files from a to b.

We want this worker to be scheduled to occur after harvesting - using the information from a freshly harvested file.

Use case: workers inside another institution (e.g. QUT) like to have a local mirror of the data.

**Comment by cofiem** [comment]
See https://github.com/QutBioacoustics/baw-workers/blob/master/lib/baw-workers/mirror/action.rb

**Comment by atruskie** [comment]
So catch me up, looks like we have the copy task, but it just needs to be integrated into the harvest task?

It seems it might also be blocked by #7?

**Comment by cofiem** [comment]
Yes, we have the copy task. It is indeed blocked by #7.

I'm not sure on the best way to 'integrate' the tasks. Maybe a whole new action: `harvest_copy`?

**Comment by atruskie** [comment]
Yeah it seems a little coupled to just add it in as a hard dependency to the harvesting.

I was half thinking, in the analysis config we could specify jobs to enqueue after execution... but maybe this idea is too complex.
