### ISSUE TITLE
Output directory customization

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-workers#13]
We need to be able to customize the output directory on the analysis job.

The output directory needs to be settable for the analysis.

There needs to be some logic that is able to calculate output directories.

The first part of the directory structure, the base directory (for us the mount point to networks storage) should be taken from the config file.

Note: this is not the same as the working directory. The working directory is where the executable operates from, but not the output destination for the files. The working directory code should remain unchanged

**Comment by cofiem** [comment]
See also: https://github.com/QutBioacoustics/baw-server/issues/207

**Comment by cofiem** [comment]
@atruskie this is per analysis?

**Comment by atruskie** [comment]
Although #16 is a little out of date, in particular the 

>Note these changes only affect the enqueue portions of the code.

>Ideally the dequeuer (the part of the code that actually executed jobs) will remain the same.

portion is a good philosophy. 

So, the actually job runner itself simply sets the output directory to whatever is set in the payload.

The "per analysis" phrasing I find confusing. The output directory will be calculated every time an analysis is _enqueued_ by the code in #20. Does this answer the question?
