### ISSUE TITLE
Copy analysis log on job completion

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-workers#15]
This idea might be better generalized by specifying an array of  globs (file patterns) to copy after the job was completed.

The files should be copied regardless of the executable failing or not.

Should be able to copy files from the AP.exe folder (specifically the Logs subdirectory), any files out of the working directory, and any files from the temp directory.

Should not be able to copy files from higher directories.

**Comment by cofiem** [comment]
@atruskie should "specifying an array of globs" be able to be done per analysis, or for every analysis (so in config file)?

**Comment by cofiem** [comment]
Might be related to #11

**Comment by atruskie** [comment]
I think this is unrelated to #11

I think the resque task (i.e. the analysis task) should copy files that match the globs specified in the payload for the task.

Architecting it with the payload (instead of a config file) allows the job to operate independently of the deployment (i.e. if in config file, workers need to be redeployed for an updated glob pattern).

Thoughts?
