### ISSUE TITLE
Harvesting: Allow inclusion of arbitrary structured meta data

### ISSUE THREAD

**Issue by atruskie** [QutBioacoustics/baw-workers#25]
Allow the harvester to add arbitrary structured metadata to audio recordings when they are harvested.

Proposal: in the `harvest.yml` add a field like `metadata` that is parsed as yaml, converted to JSON and stored in the unstructured data field for audio recordings.

Use case: record important information related to the deployment. E.g. sensor used, conditions affecting the sensor, explanation of weird data (i.e. stripped channels or non-contiguous).

**Comment by cofiem** [comment]
see also #19

**Comment by atruskie** [comment]
@cofiem so you haven't done this it would appear? Just added the instructions for it on the harvest page?

**Comment by cofiem** [comment]
Yeah, hasn't been done. Apologies. :weary:

**Comment by atruskie** [comment]
:+1: nice!
