### ISSUE TITLE
Append an extension to audio files that do not meet duration threshold

### ISSUE THREAD

**Issue by cofiem** [QutBioacoustics/baw-workers#8]
When harvesting, audio files that are too short raise an error and are ignored, but not renamed. If those files are processed again, the same error is raised again.

Instead, rename the files to append an extension (such as `.tooshort`) so they will be ignored on all subsequent harvest runs.

**Comment by cofiem** [comment]
This could also include the actual length of the file to assist with debugging and changes in the duration threshold.

**Comment by atruskie** [comment]
Slippery slope encoding information in flags. One case is okay...
